/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoServerFuncRouteImport } from './routes/demo/serverFunc'
import { Route as DemoApiFuncRouteImport } from './routes/demo/apiFunc'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoServerFuncRoute = DemoServerFuncRouteImport.update({
  id: '/demo/serverFunc',
  path: '/demo/serverFunc',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiFuncRoute = DemoApiFuncRouteImport.update({
  id: '/demo/apiFunc',
  path: '/demo/apiFunc',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/apiFunc': typeof DemoApiFuncRoute
  '/demo/serverFunc': typeof DemoServerFuncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/apiFunc': typeof DemoApiFuncRoute
  '/demo/serverFunc': typeof DemoServerFuncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/apiFunc': typeof DemoApiFuncRoute
  '/demo/serverFunc': typeof DemoServerFuncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo/apiFunc' | '/demo/serverFunc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo/apiFunc' | '/demo/serverFunc'
  id: '__root__' | '/' | '/demo/apiFunc' | '/demo/serverFunc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoApiFuncRoute: typeof DemoApiFuncRoute
  DemoServerFuncRoute: typeof DemoServerFuncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/serverFunc': {
      id: '/demo/serverFunc'
      path: '/demo/serverFunc'
      fullPath: '/demo/serverFunc'
      preLoaderRoute: typeof DemoServerFuncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/apiFunc': {
      id: '/demo/apiFunc'
      path: '/demo/apiFunc'
      fullPath: '/demo/apiFunc'
      preLoaderRoute: typeof DemoApiFuncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoApiFuncRoute: DemoApiFuncRoute,
  DemoServerFuncRoute: DemoServerFuncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
